import os

env = Environment()
env.Append(ENV={"HOME": os.getenv("HOME")})
env.Append(BUILDERS={"Beam": Builder(action="erlc -o ${TARGET.dir} $SOURCE", suffix=".beam")})
env.Beam("erf.erl")
env.Beam("expm1.erl")
env.Beam("phi.erl")
env.Beam("normal_cdf_inverse.erl")
env.Beam("gamma.erl")
